version: '3'
services:
  frontend:
    image: progetto_cattolica_frontend
    build: './frontend'
    # ports:
      # - "4000:3000"
    environment:
      APP_ENV: 'development'
    links:
      - backend

  backend:
    image: progetto_cattolica_backend
    build: './backend'
    links:
      - db

  db:
    image: progetto_cattolica_db
    build:
      context: ./script_utilita
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: process.env.DATABASE_SQL
      MYSQL_USER: process.env.DBUSER
      MYSQL_PASSWORD: process.env.DBPASSWORD
      MYSQL_ROOT_PASSWORD: process.env.DBROOTPASSWORD