var express = require('express');
var router = express.Router();

/* GET users listing. */
router.get('/', function(req, res, next) {
  res.json([
    {
      "cod_docente" : "46490",
      "cog_docente" : "SALLUSTIO",
      "nom_docente" : "GIUSEPPINA",
      "cfi_docente" : "SLLGPP56M58H454M",
      "email" : "giuseppina.sallustio@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46496",
      "cog_docente" : "DI GREGORIO",
      "nom_docente" : "FLAVIO",
      "cfi_docente" : "DGRFLV59T26A390R",
      "email" : "flavio.digregorio@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46500",
      "cog_docente" : "DI LELLA",
      "nom_docente" : "GIUSEPPE MARIA",
      "cfi_docente" : "DLLGPP60B18H501X",
      "email" : "giuseppemaria.dilella@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46527",
      "cog_docente" : "TARTAGLIONE",
      "nom_docente" : "TOMMASO",
      "cfi_docente" : "TRTTMS62R28H501K",
      "email" : "tommaso.tartaglione@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46529",
      "cog_docente" : "BALDUCCI",
      "nom_docente" : "MARIO",
      "cfi_docente" : "BLDMRA55R23F284W",
      "email" : "mario.balducci@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46300",
      "cog_docente" : "LEONE",
      "nom_docente" : "ANTONIO",
      "cfi_docente" : "LNENTN53M20F888Y",
      "email" : "antonio.leone1@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46307",
      "cog_docente" : "SALVATORI",
      "nom_docente" : "MASSIMO",
      "cfi_docente" : "SLVMSM55A21A515N",
      "email" : "massimo.salvatori@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 328,
      "des_struttura_aff" : "Istituto di medicina nucleare",
      "des_struttura_aff_eng" : "Institute of Nuclear Medicine",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46349",
      "cog_docente" : "VALENZA",
      "nom_docente" : "VENANZIO",
      "cfi_docente" : "VLNVNZ55H20H501J",
      "email" : "venanzio.valenza@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 328,
      "des_struttura_aff" : "Istituto di medicina nucleare",
      "des_struttura_aff_eng" : "Institute of Nuclear Medicine",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46350",
      "cog_docente" : "MANTINI",
      "nom_docente" : "GIOVANNA",
      "cfi_docente" : "MNTGNN53R61C632J",
      "email" : "giovanna.mantini@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46367",
      "cog_docente" : "SMANIOTTO",
      "nom_docente" : "DANIELA",
      "cfi_docente" : "SMNDNL53D42H501A",
      "email" : "daniela.smaniotto@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46584",
      "cog_docente" : "MEDURI",
      "nom_docente" : "AGOSTINO",
      "cfi_docente" : "MDRGTN62E03H501L",
      "email" : "agostino.meduri@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "52685",
      "cog_docente" : "MANFREDI",
      "nom_docente" : "RICCARDO",
      "cfi_docente" : "MNFRCR63E14H501K",
      "email" : "riccardo.manfredi@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 2,
      "des_ruolo" : "PROFESSORE ORDINARIO",
      "des_ruolo_eng" : "FULL PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "52286",
      "cog_docente" : "IEZZI",
      "nom_docente" : "ROBERTO",
      "cfi_docente" : "ZZIRRT74T31D548G",
      "email" : "roberto.iezzi@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/36              ",
      "des_ssd" : "DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA",
      "id_ruolo" : 7,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 335,
      "des_struttura_aff" : "Istituto di radiologia",
      "des_struttura_aff_eng" : "Institute of Radiology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "17570",
      "cog_docente" : "CHIARETTI",
      "nom_docente" : "ANTONIO",
      "cfi_docente" : "CHRNTN59C24H282T",
      "email" : "antonio.chiaretti@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "DIRETTORE DI ISTITUTO",
      "incarico_dir_eng" : "INSTITUTE DIRECTOR",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "15258",
      "cog_docente" : "RUGGIERO",
      "nom_docente" : "ANTONIO",
      "cfi_docente" : "RGGNTN67T01I288P",
      "email" : "antonio.ruggiero@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "35438",
      "cog_docente" : "RENDELI",
      "nom_docente" : "CLAUDIA",
      "cfi_docente" : "RNDCLD61M53H501Z",
      "email" : "claudia.rendeli@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46774",
      "cog_docente" : "MAURIZI",
      "nom_docente" : "PALMA",
      "cfi_docente" : "MRZPLM66C41L334T",
      "email" : "palma.maurizi@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46722",
      "cog_docente" : "LAZZARESCHI",
      "nom_docente" : "ILARIA",
      "cfi_docente" : "LZZLRI67R58M059Q",
      "email" : "ilaria.lazzareschi@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46723",
      "cog_docente" : "MASTRANGELO",
      "nom_docente" : "STEFANO",
      "cfi_docente" : "MSTSFN67B20H501J",
      "email" : "stefano.mastrangelo@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46599",
      "cog_docente" : "DELOGU",
      "nom_docente" : "ANGELICA BIBIANA",
      "cfi_docente" : "DLGNLC61T42G147O",
      "email" : "angelicabibiana.delogu@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46614",
      "cog_docente" : "DE ROSA",
      "nom_docente" : "GABRIELLA",
      "cfi_docente" : "DRSGRL61P46E563Z",
      "email" : "gabriella.derosa@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46618",
      "cog_docente" : "FREZZA",
      "nom_docente" : "SIMONETTA",
      "cfi_docente" : "FRZSNT64B67H501Q",
      "email" : "simonetta.frezza@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46659",
      "cog_docente" : "RIGANTE",
      "nom_docente" : "DONATO",
      "cfi_docente" : "RGNDNT66L02A883K",
      "email" : "donato.rigante@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46444",
      "cog_docente" : "MICELI SOPO",
      "nom_docente" : "STEFANO",
      "cfi_docente" : "MCLSFN58D18B429T",
      "email" : "stefano.micelisopo@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46459",
      "cog_docente" : "VALENTINI",
      "nom_docente" : "PIERO",
      "cfi_docente" : "VLNPRI58A06C352Y",
      "email" : "piero.valentini@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46462",
      "cog_docente" : "FERRARA",
      "nom_docente" : "PIETRO",
      "cfi_docente" : "FRRPTR58S11G942Y",
      "email" : "pietro.ferrara@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46329",
      "cog_docente" : "ZECCA",
      "nom_docente" : "ENRICO",
      "cfi_docente" : "ZCCNRC54T01H501A",
      "email" : "enrico.zecca@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46373",
      "cog_docente" : "LUCIANO",
      "nom_docente" : "RITA PAOLA MARIA",
      "cfi_docente" : "LCNRPL56M64H224C",
      "email" : "ritapaola.luciano@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46573",
      "cog_docente" : "MAGGIO",
      "nom_docente" : "LUCA",
      "cfi_docente" : "MGGLCU61R04H501Y",
      "email" : "luca.maggio@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46574",
      "cog_docente" : "PAPACCI",
      "nom_docente" : "PATRIZIA",
      "cfi_docente" : "PPCPRZ59D45H501H",
      "email" : "patrizia.papacci@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46576",
      "cog_docente" : "ZAMPINO",
      "nom_docente" : "GIUSEPPE",
      "cfi_docente" : "ZMPGPP61R09B519N",
      "email" : "giuseppe.zampino@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46579",
      "cog_docente" : "VENTO",
      "nom_docente" : "GIOVANNI",
      "cfi_docente" : "VNTGNN62H12D708Z",
      "email" : "giovanni.vento@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46583",
      "cog_docente" : "GALLINI",
      "nom_docente" : "FRANCESCA",
      "cfi_docente" : "GLLFNC64P51H501A",
      "email" : "francesca.gallini@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46585",
      "cog_docente" : "TORTOROLO",
      "nom_docente" : "LUCA",
      "cfi_docente" : "TRTLCU63T05D969V",
      "email" : "luca.tortorolo@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/38              ",
      "des_ssd" : "PEDIATRIA GENERALE E SPECIALISTICA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 322,
      "des_struttura_aff" : "Istituto di clinica pediatrica",
      "des_struttura_aff_eng" : "Institute of Clinical Pediatrics",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46687",
      "cog_docente" : "BATTAGLIA",
      "nom_docente" : "DOMENICA IMMACOLATA",
      "cfi_docente" : "BTTDNC65T47I600H",
      "email" : "domenicaimmacolata.battaglia@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/39              ",
      "des_ssd" : "NEUROPSICHIATRIA INFANTILE",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 334,
      "des_struttura_aff" : "Istituto di psichiatria e psicologia",
      "des_struttura_aff_eng" : "Institute of Psychiatry and Psychology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46673",
      "cog_docente" : "MERCURI",
      "nom_docente" : "EUGENIO MARIA",
      "cfi_docente" : "MRCGMR63C31C352W",
      "email" : "eugeniomaria.mercuri@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/39              ",
      "des_ssd" : "NEUROPSICHIATRIA INFANTILE",
      "id_ruolo" : 2,
      "des_ruolo" : "PROFESSORE ORDINARIO",
      "des_ruolo_eng" : "FULL PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 334,
      "des_struttura_aff" : "Istituto di psichiatria e psicologia",
      "des_struttura_aff_eng" : "Institute of Psychiatry and Psychology",
      "incarico_dir" : "DIRETTORE DI ISTITUTO",
      "incarico_dir_eng" : "INSTITUTE DIRECTOR",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46718",
      "cog_docente" : "TESTA",
      "nom_docente" : "ANTONIA CARLA",
      "cfi_docente" : "TSTNNC65S58C800D",
      "email" : "antoniacarla.testa@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46741",
      "cog_docente" : "PARADISI",
      "nom_docente" : "GIANCARLO",
      "cfi_docente" : "PRDGCR63D11H501X",
      "email" : "giancarlo.paradisi@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46619",
      "cog_docente" : "FERRANDINA",
      "nom_docente" : "MARIA GABRIELLA",
      "cfi_docente" : "FRRMGB64H60D643I",
      "email" : "mariagabriella.ferrandina@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46627",
      "cog_docente" : "VILLA",
      "nom_docente" : "PAOLA",
      "cfi_docente" : "VLLPLA60H66F463U",
      "email" : "paola.villa@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46628",
      "cog_docente" : "DI SIMONE",
      "nom_docente" : "NICOLETTA",
      "cfi_docente" : "DSMNLT63L63A859D",
      "email" : "nicoletta.disimone@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46629",
      "cog_docente" : "DE VINCENZO",
      "nom_docente" : "ROSA PASQUALINA",
      "cfi_docente" : "DVNRPS66D50D005H",
      "email" : "rosa.devincenzo@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46647",
      "cog_docente" : "GUIDO",
      "nom_docente" : "MAURIZIO",
      "cfi_docente" : "GDUMRZ65P14D086J",
      "email" : "maurizio.guido@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46815",
      "cog_docente" : "FAGOTTI",
      "nom_docente" : "ANNA",
      "cfi_docente" : "FGTNNA70S64H501A",
      "email" : "anna.fagotti@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46390",
      "cog_docente" : "ROSATI",
      "nom_docente" : "PAOLO",
      "cfi_docente" : "RSTPLA55M01A952W",
      "email" : "paolo.rosati@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46398",
      "cog_docente" : "SCAMBIA",
      "nom_docente" : "GIOVANNI",
      "cfi_docente" : "SCMGNN59T24C352H",
      "email" : "giovanni.scambia@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 2,
      "des_ruolo" : "PROFESSORE ORDINARIO",
      "des_ruolo_eng" : "FULL PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46399",
      "cog_docente" : "LANZONE",
      "nom_docente" : "ANTONIO",
      "cfi_docente" : "LNZNTN54P23D086G",
      "email" : "antonio.lanzone@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 2,
      "des_ruolo" : "PROFESSORE ORDINARIO",
      "des_ruolo_eng" : "FULL PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "DIRETTORE DI ISTITUTO",
      "incarico_dir_eng" : "INSTITUTE DIRECTOR",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46447",
      "cog_docente" : "DE CAROLIS",
      "nom_docente" : "SARA",
      "cfi_docente" : "DCRSRA57R60A462U",
      "email" : "sara.decarolis@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46546",
      "cog_docente" : "APA",
      "nom_docente" : "ROSANNA",
      "cfi_docente" : "PAARNN61A41D086Y",
      "email" : "rosanna.apa@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46331",
      "cog_docente" : "FERRAZZANI",
      "nom_docente" : "SERGIO",
      "cfi_docente" : "FRRSRG52H06M082N",
      "email" : "sergio.ferrazzani@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46338",
      "cog_docente" : "MARGARITI",
      "nom_docente" : "PASQUALE ALESSANDRO",
      "cfi_docente" : "MRGPQL52P06L117O",
      "email" : "pasqualealessandro.margariti@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46363",
      "cog_docente" : "MASINI",
      "nom_docente" : "LUCIA",
      "cfi_docente" : "MSNLCU54H44F656X",
      "email" : "lucia.masini@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46589",
      "cog_docente" : "DE SANTIS",
      "nom_docente" : "MARCO",
      "cfi_docente" : "DSNMRC61D09A123Q",
      "email" : "marco.desantis@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "56502",
      "cog_docente" : "FANFANI",
      "nom_docente" : "FRANCESCO",
      "cfi_docente" : "FNFFNC74C22H501P",
      "email" : "francesco.fanfani1@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/40              ",
      "des_ssd" : "GINECOLOGIA E OSTETRICIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 320,
      "des_struttura_aff" : "Istituto di clinica ostetrica e ginecologica",
      "des_struttura_aff_eng" : "Institute of Clinical Obstetrics and Gynaecology",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "20803",
      "cog_docente" : "PENNISI",
      "nom_docente" : "MARIANO ALBERTO",
      "cfi_docente" : "PNNMNL58M10I216T",
      "email" : "marianoalberto.pennisi@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46754",
      "cog_docente" : "MONTINI",
      "nom_docente" : "LUCA",
      "cfi_docente" : "MNTLCU69R18H501X",
      "email" : "luca.montini@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46592",
      "cog_docente" : "MODESTI",
      "nom_docente" : "CRISTINA",
      "cfi_docente" : "MDSCST65A47Z131G",
      "email" : "cristina.modesti@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46601",
      "cog_docente" : "CARICATO",
      "nom_docente" : "ANSELMO",
      "cfi_docente" : "CRCNLM65S06H501T",
      "email" : "anselmo.caricato@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46602",
      "cog_docente" : "SCAPIGLIATI",
      "nom_docente" : "ANDREA",
      "cfi_docente" : "SCPNDR66E31H501D",
      "email" : "andrea.scapigliati@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46608",
      "cog_docente" : "PULITANO'",
      "nom_docente" : "SILVIA MARIA",
      "cfi_docente" : "PLTSVM66L47H224H",
      "email" : "silviamaria.pulitano@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46615",
      "cog_docente" : "CORRADO",
      "nom_docente" : "MICHELE",
      "cfi_docente" : "CRRMHL65D26L008P",
      "email" : "michele.corrado@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46641",
      "cog_docente" : "ANTONELLI",
      "nom_docente" : "MASSIMO",
      "cfi_docente" : "NTNMSM57B23H501O",
      "email" : "massimo.antonelli@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 2,
      "des_ruolo" : "PROFESSORE ORDINARIO",
      "des_ruolo_eng" : "FULL PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46642",
      "cog_docente" : "CONTI",
      "nom_docente" : "GIORGIO",
      "cfi_docente" : "CNTGRG56S06A944C",
      "email" : "giorgio.conti@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 2,
      "des_ruolo" : "PROFESSORE ORDINARIO",
      "des_ruolo_eng" : "FULL PROFESSOR",
      "stato_ruolo" : "NC",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "DIRETTORE DI ISTITUTO",
      "incarico_dir_eng" : "INSTITUTE DIRECTOR",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46383",
      "cog_docente" : "VALENTI",
      "nom_docente" : "MARIO",
      "cfi_docente" : "VLNMRA58S17F158L",
      "email" : "mario.valenti@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46386",
      "cog_docente" : "BARELLI",
      "nom_docente" : "ALESSANDRO",
      "cfi_docente" : "BRLLSN55C17H501O",
      "email" : "alessandro.barelli@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46387",
      "cog_docente" : "BARILARO",
      "nom_docente" : "CYNTHIA",
      "cfi_docente" : "BRLCNT57M56H501K",
      "email" : "cynthia.barilaro@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46389",
      "cog_docente" : "GUALTIERI",
      "nom_docente" : "ELISABETTA",
      "cfi_docente" : "GLTLBT57T50C794R",
      "email" : "elisabetta.gualtieri@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46393",
      "cog_docente" : "PERILLI",
      "nom_docente" : "VALTER",
      "cfi_docente" : "PRLVTR56D03A345D",
      "email" : "valter.perilli@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46395",
      "cog_docente" : "PEROTTI",
      "nom_docente" : "VALERIO",
      "cfi_docente" : "PRTVLR57M11H501F",
      "email" : "valerio.perotti@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46407",
      "cog_docente" : "ZAMPARELLI",
      "nom_docente" : "ROBERTO",
      "cfi_docente" : "ZMPRRT56P15H501I",
      "email" : "roberto.zamparelli@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46433",
      "cog_docente" : "CREA",
      "nom_docente" : "MARIA ANTONIETTA",
      "cfi_docente" : "CREMNT59M53H224B",
      "email" : "mariaantonietta.crea@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46440",
      "cog_docente" : "ROSSI",
      "nom_docente" : "MARCO",
      "cfi_docente" : "RSSMRC59E10A271B",
      "email" : "marco.rossi1@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 3,
      "des_ruolo" : "PROFESSORE ASSOCIATO",
      "des_ruolo_eng" : "ASSOCIATE PROFESSOR",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    },
    {
      "cod_docente" : "46456",
      "cog_docente" : "MIGNANI",
      "nom_docente" : "VITTORIO",
      "cfi_docente" : "MGNVTR54T05F205H",
      "email" : "vittorio.mignani@unicatt.it",
      "cod_sede" : "10",
      "des_sede" : "Roma",
      "cod_facolta" : "75012",
      "des_facolta" : "MEDICINA E CHIRURGIA \"A.GEMELLI\"",
      "des_facolta_eng" : "MEDICINE AND SURGERY",
      "cod_ssd" : "MED/41              ",
      "des_ssd" : "ANESTESIOLOGIA",
      "id_ruolo" : 1,
      "des_ruolo" : "RICERCATORE",
      "des_ruolo_eng" : "RESEARCHER",
      "stato_ruolo" : "CO",
      "cod_sede_aff" : "10",
      "des_sede_aff" : "Roma",
      "id_struttura_aff" : 323,
      "des_struttura_aff" : "Istituto di anestesiologia e rianimazione",
      "des_struttura_aff_eng" : "Institute of Anesthesiology and Intensive care",
      "incarico_dir" : "",
      "incarico_dir_eng" : "",
      "ente_provenienza" : ""
    }
  ]);
});

module.exports = router;
